In [202]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error,accuracy_score

In [203]:
data = pd.read_csv("heart.csv")

In [204]:
data.shape

(303, 14)

In [205]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trtbps    303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalachh  303 non-null    int64
 8   exng      303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slp       303 non-null    int64
 11  caa       303 non-null    int64
 12  thall     303 non-null    int64
 13  output    303 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 33.3 KB

In [206]:
df = data.copy()

In [207]:
df.head()

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [208]:
X = df.drop("output",axis=1)
y = df["output"]

In [209]:
X

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2

In [210]:
y

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: output, Length: 303, dtype: int64

In [211]:
X_train,X_test,y_train,y_test = train_test_split(X,y,train_size = 0.80,random_state = 42)

In [212]:
X_train

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall
132,42,1,1,120,295,0,1,162,0,0.0,2,0,2
202,58,1,0,150,270,0,0,111,1,0.8,2,0,3
196,46,1,2,150,231,0,1,147,0,3.6,1,0,2
75,55,0,1,135,250,0,0,161,0,1.4,1,0,2
176,60,1,0,117,230,1,1,160,1,1.4,2,2,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
188,50,1,2,140,233,0,1,163,0,0.6,1,1,3
71,51,1,2,94,227,0,1,154,1,0.0,2,1,3
106,69,1,3,160,234,1,0,131,0,0.1,1,1,2
270,46,1,0,120,249,0,0,144,0,0.8,2,0,3
102,63,0,1,140,195,0,1,179,0,0.0,2,2,2

In [213]:
X_test

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall
179,57,1,0,150,276,0,0,112,1,0.6,1,1,1
228,59,1,3,170,288,0,0,159,0,0.2,1,0,3
111,57,1,2,150,126,1,1,173,0,0.2,2,1,3
246,56,0,0,134,409,0,0,150,1,1.9,1,2,3
60,71,0,2,110,265,1,0,130,0,0.0,2,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
249,69,1,2,140,254,0,0,146,0,2.0,1,3,3
104,50,1,2,129,196,0,1,163,0,0.0,2,0,2
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3
193,60,1,0,145,282,0,0,142,1,2.8,1,2,3
184,50,1,0,150,243,0,0,128,0,2.6,1,0,3

In [214]:
model = LogisticRegression()

In [215]:
model.fit(X_train,y_train)

/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [216]:
predicts = model.predict(X_test)
predicts

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0])

In [217]:
temp_y_test = np.array(y_test)
for i in range(len(predicts)):
  print(f"{i} - tahmini deger : {predicts[i]} - gercek deger : {temp_y_test[i]}")

0 - tahmini deger : 0 - gercek deger : 0
1 - tahmini deger : 1 - gercek deger : 0
2 - tahmini deger : 1 - gercek deger : 1
3 - tahmini deger : 0 - gercek deger : 0
4 - tahmini deger : 1 - gercek deger : 1
5 - tahmini deger : 1 - gercek deger : 1
6 - tahmini deger : 1 - gercek deger : 1
7 - tahmini deger : 0 - gercek deger : 0
8 - tahmini deger : 0 - gercek deger : 0
9 - tahmini deger : 1 - gercek deger : 1
10 - tahmini deger : 1 - gercek deger : 1
11 - tahmini deger : 0 - gercek deger : 1
12 - tahmini deger : 1 - gercek deger : 1
13 - tahmini deger : 0 - gercek deger : 0
14 - tahmini deger : 1 - gercek deger : 1
15 - tahmini deger : 1 - gercek deger : 1
16 - tahmini deger : 1 - gercek deger : 1
17 - tahmini deger : 0 - gercek deger : 0
18 - tahmini deger : 0 - gercek deger : 0
19 - tahmini deger : 0 - gercek deger : 0
20 - tahmini deger : 1 - gercek deger : 1
21 - tahmini deger : 0 - gercek deger : 0
22 - tahmini deger : 0 - gercek deger : 0
23 - tahmini deger : 1 - gercek deger : 1
24 - tahmini deger : 1 - gercek deger : 1
25 - tahmini deger : 1 - gercek deger : 0
26 - tahmini deger : 1 - gercek deger : 0
27 - tahmini deger : 1 - gercek deger : 1
28 - tahmini deger : 0 - gercek deger : 0
29 - tahmini deger : 1 - gercek deger : 1
30 - tahmini deger : 0 - gercek deger : 1
31 - tahmini deger : 0 - gercek deger : 0
32 - tahmini deger : 0 - gercek deger : 0
33 - tahmini deger : 0 - gercek deger : 1
34 - tahmini deger : 1 - gercek deger : 1
35 - tahmini deger : 0 - gercek deger : 0
36 - tahmini deger : 1 - gercek deger : 1
37 - tahmini deger : 1 - gercek deger : 1
38 - tahmini deger : 1 - gercek deger : 1
39 - tahmini deger : 1 - gercek deger : 1
40 - tahmini deger : 1 - gercek deger : 1
41 - tahmini deger : 1 - gercek deger : 1
42 - tahmini deger : 1 - gercek deger : 1
43 - tahmini deger : 1 - gercek deger : 1
44 - tahmini deger : 1 - gercek deger : 1
45 - tahmini deger : 0 - gercek deger : 0
46 - tahmini deger : 1 - gercek deger : 0
47 - tahmini deger : 1 - gercek deger : 1
48 - tahmini deger : 0 - gercek deger : 0
49 - tahmini deger : 0 - gercek deger : 0
50 - tahmini deger : 0 - gercek deger : 0
51 - tahmini deger : 0 - gercek deger : 0
52 - tahmini deger : 1 - gercek deger : 1
53 - tahmini deger : 1 - gercek deger : 1
54 - tahmini deger : 0 - gercek deger : 0
55 - tahmini deger : 0 - gercek deger : 0
56 - tahmini deger : 0 - gercek deger : 0
57 - tahmini deger : 1 - gercek deger : 1
58 - tahmini deger : 0 - gercek deger : 0
59 - tahmini deger : 0 - gercek deger : 0
60 - tahmini deger : 0 - gercek deger : 0

In [218]:
model_score = model.score(X_test,y_test)
model_score

0.8852459016393442

In [219]:
acc_score = accuracy_score(y_test,predicts) # sınıflandırma modellerinde r2_score yerine accuracy_score kullanılır!
acc_score

0.8852459016393442